# Generated by Django 5.2.17 on 2026-09-26 14:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_wishlist'),
        ('sales', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique promotional code (e.g. MAISON10, VVIP500)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description of the promotional privilege', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', help_text='Whether discount is percentage or fixed amount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g. 15.00 for 15%) or flat amount in INR (e.g. 500.00)', max_digits=10)),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required to redeem this voucher', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on discount amount for percentage vouchers', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time when voucher becomes active')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Expiration date and time (leave blank for no expiry)', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total allowed redemptions (leave blank for unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Total number of times this voucher has been redeemed')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this voucher can be currently used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specific_customer', models.ForeignKey(blank=True, help_text='Restricts redemption to a specific customer account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
