# Generated by Django 5.2.17 on 2026-10-01 16:34

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Maison Moménto', help_text='Official name of the luxury maison.', max_length=255, verbose_name='Business Name')),
                ('business_email', models.EmailField(default='concierge@maisonmomento.com', help_text='Primary email for client concierge inquiries.', max_length=255, verbose_name='Business Email')),
                ('primary_phone', models.CharField(default='+33 1 40 20 50 50', help_text='Main telephone number for the boutique.', max_length=50, validators=[dashboard.models.validate_phone_number], verbose_name='Primary Phone Number')),
                ('secondary_phone', models.CharField(blank=True, default='', help_text='Optional secondary contact or helpline.', max_length=50, validators=[dashboard.models.validate_phone_number], verbose_name='Secondary Phone Number (optional)')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Optional WhatsApp concierge number (with country code).', max_length=50, validators=[dashboard.models.validate_phone_number], verbose_name='WhatsApp Number (optional)')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/maisonmomento', help_text='Official Instagram profile link.', max_length=500, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, default='', help_text='Official Facebook page link.', max_length=500, verbose_name='Facebook URL (optional)')),
                ('linkedin_url', models.URLField(blank=True, default='', help_text='Official LinkedIn company page link.', max_length=500, verbose_name='LinkedIn URL (optional)')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='Official X / Twitter profile link (not displayed by default).', max_length=500, verbose_name='X / Twitter URL (optional)')),
                ('business_address', models.TextField(default='15 Rue de la Paix\n75002 Paris\nFrance', help_text='Physical boutique address displayed on the storefront.', verbose_name='Business Address')),
                ('google_maps_url', models.URLField(blank=True, default='', help_text='Direct link to the boutique location on Google Maps.', max_length=500, verbose_name='Google Maps URL (optional)')),
                ('business_hours', models.TextField(default='Monday – Friday: 10:00 AM – 7:00 PM (CET)\nSaturday: 11:00 AM – 5:00 PM (CET)\nSunday: Closed', help_text='Opening and concierge availability hours.', verbose_name='Business Hours')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Business Contact Setting',
                'verbose_name_plural': 'Business Contact Settings',
            },
        ),
    ]
