# Generated by Django 5.2.17 on 2026-10-01 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='admin_avatars/', verbose_name='Profile Picture')),
                ('display_title', models.CharField(blank=True, default='Maison Administrator', max_length=100, verbose_name='Title / Role')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Direct Telephone')),
                ('timezone', models.CharField(blank=True, default='Europe/Paris (CET)', max_length=50, verbose_name='Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
    ]
