# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_price'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Viewed Product'), ('search', 'Search'), ('wishlist', 'Wishlist'), ('cart', 'Added to Cart'), ('purchase', 'Purchase'), ('recommendation_click', 'Recommendation Click')], default='PRODUCT_VIEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='catalog.product')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tracking.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
