# Generated by Django 6.1.1 on 2026-09-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous visitor session identifier', max_length=100)),
                ('interaction_type', models.CharField(choices=[('PRODUCT_VIEW', 'Product View'), ('PRODUCT_CLICK', 'Product Click')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, help_text='Associated customer account if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
