# Generated by Django 5.2.17 on 2026-09-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price'),
        ('recommendations', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='event_type',
            field=models.CharField(choices=[('view', 'Viewed Product'), ('search', 'Search'), ('wishlist', 'Wishlist'), ('cart', 'Added to Cart'), ('purchase', 'Purchase'), ('recommendation_click', 'Recommendation Click')], db_index=True, default='view', max_length=30),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['product', 'event_type', 'created_at'], name='interaction_product_event_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['visitor', 'event_type', 'created_at'], name='interaction_visitor_event_idx'),
        ),
    ]
