# Generated by Django 5.2.17 on 2026-09-14 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='The delta amount by which the stock changed (positive or negative).')),
                ('previous_stock', models.PositiveIntegerField(help_text='Stock before the adjustment.')),
                ('new_stock', models.PositiveIntegerField(help_text='Stock after the adjustment.')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('restock', 'Restock'), ('damaged', 'Damaged'), ('manual_correction', 'Manual Correction')], help_text='The nature of the adjustment.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Explanation or context for this adjustment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The admin user who performed this adjustment (null for automated system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product whose stock was adjusted.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
