# Generated by Django 6.1.1 on 2026-09-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Client session identifier', max_length=100)),
                ('event_type', models.CharField(choices=[('PRODUCT_VIEW', 'Product View'), ('PRODUCT_CLICK', 'Product Click'), ('ADD_TO_CART', 'Add to Cart'), ('REMOVE_FROM_CART', 'Remove from Cart'), ('CHECKOUT_STARTED', 'Checkout Started'), ('PURCHASE', 'Purchase'), ('RECOMMENDATION_VIEW', 'Recommendation View'), ('RECOMMENDATION_CLICK', 'Recommendation Click'), ('WHATSAPP_CLICK', 'WhatsApp Click'), ('INSTAGRAM_CLICK', 'Instagram Click')], db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary telemetry metadata (UTM tags, device info, referrers)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, help_text='Customer profile if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
