# Generated by Django 6.1.1 on 2026-09-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Woody, Oud, Floral)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Olfactory profile and category description')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is active in catalog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand', models.CharField(db_index=True, default='Maison Momento', max_length=150)),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit', max_length=64, unique=True)),
                ('description', models.TextField(help_text='Detailed scent notes, accord composition, and description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail price in USD', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Promotional discount price (optional)', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Current available inventory quantity')),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women')], default='unisex', max_length=20)),
                ('fragrance_family', models.CharField(choices=[('woody', 'Woody'), ('oud', 'Oud'), ('fresh', 'Fresh'), ('floral', 'Floral'), ('citrus', 'Citrus'), ('gourmand', 'Gourmand'), ('oriental', 'Oriental'), ('musky', 'Musky')], default='woody', help_text='Olfactory fragrance family', max_length=50)),
                ('concentration', models.CharField(choices=[('parfum', 'Parfum / Extrait de Parfum'), ('edp', 'Eau de Parfum (EDP)'), ('edt', 'Eau de Toilette (EDT)'), ('edc', 'Eau de Cologne (EDC)'), ('eau_fraiche', 'Eau Fraîche')], default='edp', help_text='Perfume oil concentration', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Display prominently on featured showcase')),
                ('is_active', models.BooleanField(default=True, help_text='Product visibility status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary fragrance classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Designate this image as the main showcase image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which image appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
