# Generated by Django 5.2.17 on 2026-09-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price'),
        ('customers', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default='Maison Momènto', max_length=150),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Display name of reviewer', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating between 1 and 5')),
                ('title', models.CharField(blank=True, help_text='Optional review title', max_length=255)),
                ('comment', models.TextField(help_text='Review content / olfactory impression')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Verified customer purchase status')),
                ('is_approved', models.BooleanField(default=True, help_text='Designates whether review is approved and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='customers.customer')),
                ('product', models.ForeignKey(help_text='Product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
