# Generated by Django 5.2.17 on 2026-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_occasion_product_occasions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Olfactory note name (e.g. Bergamot, Rose, Oud)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Scent profile and olfactory characteristics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fragrance Note',
                'verbose_name_plural': 'Fragrance Notes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.ManyToManyField(blank=True, help_text='Base / Foundation notes that linger on the skin for hours', related_name='base_note_products', to='catalog.fragrancenote'),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.ManyToManyField(blank=True, help_text='Heart / Middle notes forming the core character of the fragrance', related_name='heart_note_products', to='catalog.fragrancenote'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.ManyToManyField(blank=True, help_text='Top / Opening notes (evaporate within 15–30 minutes)', related_name='top_note_products', to='catalog.fragrancenote'),
        ),
    ]
